services:
  backend:
    build: ./colorful-footwear-site/backend
    container_name: footwear-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./colorful-footwear-site/frontend
    container_name: footwear-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
